import {createSlice} from '@reduxjs/toolkit';

const initialState = [
  {
    id: 1,
    firstName: 'Ahmet',
    lastName: 'Yılmaz',
    dateOfEmployment: '2020-01-15',
    dateOfBirth: '1985-05-20',
    phoneNumber: '5551234567',
    emailAddress: 'ahmet.yilmaz@example.com',
    department: 'analytics',
    position: 'junior',
  },
  {
    id: 2,
    firstName: 'Ayşe',
    lastName: 'Kara',
    dateOfEmployment: '2021-06-10',
    dateOfBirth: '1990-09-12',
    phoneNumber: '5559876543',
    emailAddress: 'ayse.kara@example.com',
    department: 'tech',
    position: 'medior',
  },
  {
    id: 3,
    firstName: 'Mehmet',
    lastName: 'Demir',
    dateOfEmployment: '2019-11-25',
    dateOfBirth: '1983-03-14',
    phoneNumber: '5552345678',
    emailAddress: 'mehmet.demir@example.com',
    department: 'analytics',
    position: 'senior',
  },
  {
    id: 4,
    firstName: 'Fatma',
    lastName: 'Çelik',
    dateOfEmployment: '2022-02-20',
    dateOfBirth: '1995-07-30',
    phoneNumber: '5553456789',
    emailAddress: 'fatma.celik@example.com',
    department: 'tech',
    position: 'junior',
  },
  {
    id: 5,
    firstName: 'Emre',
    lastName: 'Şahin',
    dateOfEmployment: '2018-09-15',
    dateOfBirth: '1987-11-22',
    phoneNumber: '5554567890',
    emailAddress: 'emre.sahin@example.com',
    department: 'analytics',
    position: 'medior',
  },
  {
    id: 6,
    firstName: 'Hülya',
    lastName: 'Özkan',
    dateOfEmployment: '2021-03-12',
    dateOfBirth: '1992-08-10',
    phoneNumber: '5555678901',
    emailAddress: 'hulya.ozkan@example.com',
    department: 'tech',
    position: 'senior',
  },
  {
    id: 7,
    firstName: 'Ali',
    lastName: 'Turan',
    dateOfEmployment: '2020-07-18',
    dateOfBirth: '1989-12-25',
    phoneNumber: '5556789012',
    emailAddress: 'ali.turan@example.com',
    department: 'analytics',
    position: 'junior',
  },
  {
    id: 8,
    firstName: 'Zeynep',
    lastName: 'Aydın',
    dateOfEmployment: '2019-05-06',
    dateOfBirth: '1993-02-18',
    phoneNumber: '5557890123',
    emailAddress: 'zeynep.aydin@example.com',
    department: 'tech',
    position: 'medior',
  },
  {
    id: 9,
    firstName: 'Mustafa',
    lastName: 'Koç',
    dateOfEmployment: '2022-04-01',
    dateOfBirth: '1996-10-05',
    phoneNumber: '5558901234',
    emailAddress: 'mustafa.koc@example.com',
    department: 'analytics',
    position: 'senior',
  },
  {
    id: 10,
    firstName: 'Elif',
    lastName: 'Arslan',
    dateOfEmployment: '2020-08-10',
    dateOfBirth: '1988-06-15',
    phoneNumber: '5559012345',
    emailAddress: 'elif.arslan@example.com',
    department: 'tech',
    position: 'junior',
  },
  {
    id: 11,
    firstName: 'Murat',
    lastName: 'Bozkurt',
    dateOfEmployment: '2021-01-03',
    dateOfBirth: '1984-04-28',
    phoneNumber: '5550123456',
    emailAddress: 'murat.bozkurt@example.com',
    department: 'analytics',
    position: 'medior',
  },
  {
    id: 12,
    firstName: 'Seda',
    lastName: 'Uslu',
    dateOfEmployment: '2022-07-25',
    dateOfBirth: '1991-03-03',
    phoneNumber: '5551234560',
    emailAddress: 'seda.uslu@example.com',
    department: 'tech',
    position: 'senior',
  },
  {
    id: 13,
    firstName: 'Eren',
    lastName: 'Eren',
    dateOfEmployment: '2020-03-15',
    dateOfBirth: '1990-01-01',
    phoneNumber: '5552345671',
    emailAddress: 'eren.eren@example.com',
    department: 'analytics',
    position: 'junior',
  },
  {
    id: 14,
    firstName: 'Sevgi',
    lastName: 'Yıldırım',
    dateOfEmployment: '2019-08-09',
    dateOfBirth: '1986-09-14',
    phoneNumber: '5553456782',
    emailAddress: 'sevgi.yildirim@example.com',
    department: 'tech',
    position: 'medior',
  },
  {
    id: 15,
    firstName: 'Barış',
    lastName: 'Doğan',
    dateOfEmployment: '2018-11-01',
    dateOfBirth: '1985-07-19',
    phoneNumber: '5554567893',
    emailAddress: 'baris.dogan@example.com',
    department: 'analytics',
    position: 'senior',
  },
  {
    id: 16,
    firstName: 'Nur',
    lastName: 'Aksoy',
    dateOfEmployment: '2021-02-19',
    dateOfBirth: '1994-10-21',
    phoneNumber: '5555678904',
    emailAddress: 'nur.aksoy@example.com',
    department: 'tech',
    position: 'junior',
  },
  {
    id: 17,
    firstName: 'Kemal',
    lastName: 'Yavuz',
    dateOfEmployment: '2019-12-12',
    dateOfBirth: '1988-02-14',
    phoneNumber: '5556789015',
    emailAddress: 'kemal.yavuz@example.com',
    department: 'analytics',
    position: 'medior',
  },
  {
    id: 18,
    firstName: 'Aslı',
    lastName: 'Çetin',
    dateOfEmployment: '2022-01-30',
    dateOfBirth: '1995-05-11',
    phoneNumber: '5557890126',
    emailAddress: 'asli.cetin@example.com',
    department: 'tech',
    position: 'senior',
  },
  {
    id: 19,
    firstName: 'Volkan',
    lastName: 'Polat',
    dateOfEmployment: '2020-05-15',
    dateOfBirth: '1991-12-03',
    phoneNumber: '5558901237',
    emailAddress: 'volkan.polat@example.com',
    department: 'analytics',
    position: 'junior',
  },
  {
    id: 20,
    firstName: 'Derya',
    lastName: 'Güneş',
    dateOfEmployment: '2021-10-04',
    dateOfBirth: '1993-08-30',
    phoneNumber: '5559012348',
    emailAddress: 'derya.gunes@example.com',
    department: 'tech',
    position: 'medior',
  },
  {
    id: 21,
    firstName: 'Hakan',
    lastName: 'Efe',
    dateOfEmployment: '2022-06-01',
    dateOfBirth: '1987-04-10',
    phoneNumber: '5550123459',
    emailAddress: 'hakan.efe@example.com',
    department: 'analytics',
    position: 'senior',
  },
  {
    id: 22,
    firstName: 'Gül',
    lastName: 'Ersoy',
    dateOfEmployment: '2020-09-10',
    dateOfBirth: '1989-11-25',
    phoneNumber: '5551234567',
    emailAddress: 'gul.ersoy@example.com',
    department: 'tech',
    position: 'junior',
  },
  {
    id: 23,
    firstName: 'Oğuz',
    lastName: 'Akgün',
    dateOfEmployment: '2019-03-20',
    dateOfBirth: '1983-07-01',
    phoneNumber: '5552345678',
    emailAddress: 'oguz.akgun@example.com',
    department: 'analytics',
    position: 'medior',
  },
  {
    id: 24,
    firstName: 'Bahar',
    lastName: 'Korkmaz',
    dateOfEmployment: '2022-08-15',
    dateOfBirth: '1990-06-12',
    phoneNumber: '5553456789',
    emailAddress: 'bahar.korkmaz@example.com',
    department: 'tech',
    position: 'senior',
  },
];

const employeesSlice = createSlice({
  name: 'employees',
  initialState: initialState,
  reducers: {
    setEmployees: (state, action) => {
      state = [];
      state.push(action.payload);
    },
    addEmployee: (state, action) => {
      const nextId = state[state.length - 1].id + 1;
      state.push({id: nextId, ...action.payload});
    },
    updateEmployee: (state, action) => {
      const index = state.findIndex(
        (employee) => employee.id === action.payload.id
      );
      if (index !== -1) {
        state[index] = action.payload;
      }
    },
    deleteEmployee: (state, action) => {
      return state.filter((employee) => employee.id !== action.payload);
    },
  },
});

export const {addEmployee, updateEmployee, deleteEmployee, setEmployees} =
  employeesSlice.actions;

export default employeesSlice.reducer;
